### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [DatapointMedia/addaptive-pixel-gtm#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.clientHash when generating the url
const url = 'https://s.dpmsrv.com/'+data.clientHash+'.min.js';

**Comment by daum** [comment]
@praveena-pappu This is all set, I hadn't done that earlier due to the regex that validates the clientHash input would not allow out any special or other characters that needed URL encoding.  I've updated it to include the encodeUriComponent just in case that validation isn't applied for any reason.
